# Dependencies
markdown:	kramdown
highlighter:	pygments

# Permalinks
permalink:	/blog/:title

# Setup
title:		Joe Timmer
tagline:	'blog'
description:	'My personal blog.'
url:		http://profsmallpine.github.io/
commentsystem:	google
disqus:		profsmallpine

author:
  name:		'Joseph Timmer'
  url:		https://plus.google.com/+JosephTimmer

paginate:	5

# Custom vars
icon:		/assets/images/icon.png
cover:  /assets/images/TheCity_18.jpg

social:
  - icon:	twitter
    url:	https://twitter.com/ProfSmallPine
    desc:	Follow me on twitter

  - icon:	github
    url:	https://github.com/profsmallpine
    desc:	Fork me on github

  - icon:	googleplus-alt
    url:	https://plus.google.com/+JosephTimmer
    desc:	Add me on google+

    
menu:
  - title:	Home
    url:	/
    
  - title:	About
    url:	/about
    
copyright:
  author:	profsmallpine
  url:		http://profsmallpine.github.io
  type_title:	Some rights reserved
  type_url:	http://creativecommons.org/licenses/by-nc/2.5

# Google Analytics (add the UA Code, e.g.: UA-xxxxxxxx-1)
google_analytics:
