# Dependencies
markdown:	redcarpet
highlighter:	true

# Permalinks
permalink:	/blog/:title

# Setup
title:		jtimmer
tagline:	'blog'
description:	'My personal blog.'
url:		http://jtimmer89.github.io/

author:
  name:		'Joseph Timmer'
  url:		https://plus.google.com/+JosephTimmer

paginate:	5

# Custom vars
icon:		/assets/images/icon.png
cover:	/assets/images/TheCity_18.jpg

social:
  - icon:	twitter
    url:	https://twitter.com/ProfSmallPine
    desc:	Follow me on twitter

  - icon:	github
    url:	https://github.com/jtimmer89
    desc:	Fork me on github

  - icon:	googleplus-alt
    url:	https://plus.google.com/+JosephTimmer
    desc:	Add me on google+
menu:
  - title:	Home
    url:	/
  - title:	About
    url:	/about
copyright:
  author:	Camporez
  url:		http://camporez.com
  type_title:	Some rights reserved
  type_url:	http://creativecommons.org/licenses/by-nc/2.5
